{
 "title": "TSDuck Prometheus",
 "time": { "from": "2023-04-12T11:39:03.559Z", "to": "2023-04-12T13:36:19.515Z" },
 "panels": [
  {
   "title": "TS Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "ts_bitrate_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TS PID Structure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ts_pid_bitrate_bytes{}",
     "legendFormat": "PID {{pid_hexadecimal}} ({{description}})"
    }
   ]
  },
  {
   "title": "TS PID Structure",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "ts_pid_bitrate_bytes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Invalid TS Sync Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ts_packet_invalid_sync_total{})",
     "legendFormat": "PID {{pid_hexadecimal}}, {{description}}"
    }
   ]
  },
  {
   "title": "Total Duplicated Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ts_pid_duplicated_total{})",
     "legendFormat": "PID {{pid_hexadecimal}}, {{description}}"
    }
   ]
  },
  {
   "title": "Transport Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ts_packet_tei_count_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCR PID Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ts_", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unreferenced PID Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ts_pid_unreferenced_count_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PID Continuity Errors",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ts_pid_discontinuities_total[$__interval])",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "PID Repetition (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "ts_pid_min_repitition_ms",
     "legendFormat": "Min Repetition:  PID {{pid_hexadecimal}}"
    },
    {
     "expr": "ts_pid_max_repitition_ms",
     "legendFormat": "Max Repetition: PID {{pid_hexadecimal}}"
    }
   ]
  },
  {
   "title": "PID Repetition (pkt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "ts_pid_min_repitition_ms{}",
     "legendFormat": "Min Repetition: PID {{pid_hexadecimal}}"
    },
    {
     "expr": "ts_pid_max_repitition_ms{}",
     "legendFormat": "Max Repetition: PID {{pid_hexadecimal}}"
    }
   ]
  }
 ]
}